import { Injectable } from '@nestjs/common';

import { isDefined } from 'twenty-shared/utils';

import { type WorkspaceAuthContext } from 'src/engine/core-modules/auth/types/workspace-auth-context.type';
import { GlobalWorkspaceOrmManager } from 'src/engine/twenty-orm/global-workspace-datasource/global-workspace-orm.manager';
import { buildSystemAuthContext } from 'src/engine/twenty-orm/utils/build-system-auth-context.util';

// Mirror-write for personRelationship: when a canonical row is created
// (person=A, relatedPerson=B, type=CHILD), a mirror row is auto-created from
// B's perspective (person=B, relatedPerson=A, type=PARENT). The mirror row's
// `mirrorOfId` points back to the canonical — that's the loop-guard: any hook
// short-circuits when `mirrorOfId IS NOT NULL`, so mirror writes never cascade
// further. Updates on canonical sync the mirror; deletes cascade.
//
// All mirror writes use a system auth context with `shouldBypassPermissionChecks`
// — the same pattern as PersonRelationshipNameService — so the hook never fails
// because the caller (API key, restricted Sales Manager) lacks permission on
// personRelationship.

type RelationshipRow = {
  id: string;
  personId?: string | null;
  relatedPersonId?: string | null;
  relationType?: string | null;
  mirrorOfId?: string | null;
};

// Symmetric types map to themselves; asymmetric (CHILD/PARENT) invert.
const INVERSE_RELATION_TYPE: Record<string, string> = {
  SPOUSE: 'SPOUSE',
  PARTNER: 'PARTNER',
  SIBLING: 'SIBLING',
  OTHER: 'OTHER',
  CHILD: 'PARENT',
  PARENT: 'CHILD',
};

@Injectable()
export class PersonRelationshipMirrorService {
  constructor(
    private readonly globalWorkspaceOrmManager: GlobalWorkspaceOrmManager,
  ) {}

  inverseType(type: string | null | undefined): string | undefined {
    if (!type) return undefined;

    return INVERSE_RELATION_TYPE[type] ?? type;
  }

  // True if the row was authored by the user / external API (canonical),
  // false if it was auto-generated by this service (mirror).
  isCanonical(row: { mirrorOfId?: string | null }): boolean {
    return !isDefined(row.mirrorOfId);
  }

  // Create the mirror counterpart of a canonical row. Idempotent: if a mirror
  // already exists for this canonical, it's a no-op.
  async createMirrorFor(
    authContext: WorkspaceAuthContext,
    canonical: RelationshipRow,
  ): Promise<void> {
    if (!this.isCanonical(canonical)) return;
    if (
      !isDefined(canonical.personId) ||
      !isDefined(canonical.relatedPersonId) ||
      !isDefined(canonical.relationType)
    ) {
      return;
    }

    const workspaceId = authContext.workspace?.id;

    if (!workspaceId) return;

    const systemAuthContext = buildSystemAuthContext(workspaceId);

    await this.globalWorkspaceOrmManager.executeInWorkspaceContext(async () => {
      const repository =
        await this.globalWorkspaceOrmManager.getRepository<any>(
          workspaceId,
          'personRelationship',
          { shouldBypassPermissionChecks: true },
        );

      const existing = await repository.findOne({
        where: { mirrorOfId: canonical.id },
      });

      if (existing) return;

      await repository.insert({
        personId: canonical.relatedPersonId,
        relatedPersonId: canonical.personId,
        relationType: this.inverseType(canonical.relationType),
        mirrorOfId: canonical.id,
      });
    }, systemAuthContext);
  }

  // Sync the mirror's fields when the canonical's people or type change.
  // Called after a canonical row update. The mirror's own update fires its
  // post-update hook too, but that hook checks `isCanonical` and skips.
  async syncMirrorFor(
    authContext: WorkspaceAuthContext,
    canonical: RelationshipRow,
  ): Promise<void> {
    if (!this.isCanonical(canonical)) return;

    const workspaceId = authContext.workspace?.id;

    if (!workspaceId) return;

    const systemAuthContext = buildSystemAuthContext(workspaceId);

    await this.globalWorkspaceOrmManager.executeInWorkspaceContext(async () => {
      const repository =
        await this.globalWorkspaceOrmManager.getRepository<any>(
          workspaceId,
          'personRelationship',
          { shouldBypassPermissionChecks: true },
        );

      const mirror = await repository.findOne({
        where: { mirrorOfId: canonical.id },
      });

      if (!mirror) {
        // Canonical exists but has no mirror — create one now (e.g. row
        // pre-existed mirror-write feature).
        await this.createMirrorFor(authContext, canonical);

        return;
      }

      await repository.update(
        { id: mirror.id },
        {
          personId: canonical.relatedPersonId,
          relatedPersonId: canonical.personId,
          relationType: this.inverseType(canonical.relationType),
        },
      );
    }, systemAuthContext);
  }

  // Delete the mirror after the canonical is deleted (soft-delete → soft;
  // destroy → destroy). We default to soft-delete since the typical UI op is
  // `deleteOne` (soft).
  async deleteMirrorFor(
    authContext: WorkspaceAuthContext,
    canonical: RelationshipRow,
  ): Promise<void> {
    if (!this.isCanonical(canonical)) return;

    const workspaceId = authContext.workspace?.id;

    if (!workspaceId) return;

    const systemAuthContext = buildSystemAuthContext(workspaceId);

    await this.globalWorkspaceOrmManager.executeInWorkspaceContext(async () => {
      const repository =
        await this.globalWorkspaceOrmManager.getRepository<any>(
          workspaceId,
          'personRelationship',
          { shouldBypassPermissionChecks: true },
        );

      const mirror = await repository.findOne({
        where: { mirrorOfId: canonical.id },
      });

      if (!mirror) return;

      await repository.softDelete({ id: mirror.id });
    }, systemAuthContext);
  }
}
