import { Field, InputType, ObjectType } from '@nestjs/graphql';

import {
  IsArray,
  IsDate,
  IsEmail,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';

@InputType('EnsoManualLeadDuplicateCheckInput')
export class EnsoManualLeadDuplicateCheckInput {
  @Field(() => String)
  @IsUUID()
  projectId: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  phoneNumber?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  phoneCallingCode?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsEmail()
  email?: string;
}

// What adding the lead would do, before anything is written. Identity is
// masked: a manager who already has the number recognises it, one who does not
// still cannot use it.
@ObjectType('EnsoManualLeadDuplicateCheck')
export class EnsoManualLeadDuplicateCheckDTO {
  // NEW | REUSE | BLOCKED
  @Field(() => String)
  verdict: string;

  @Field(() => String, { nullable: true })
  displayName: string | null;

  @Field(() => String, { nullable: true })
  maskedPhone: string | null;

  @Field(() => String, { nullable: true })
  maskedEmail: string | null;

  // BLOCKED: the colleague who works this contact on the project.
  @Field(() => String, { nullable: true })
  ownerName: string | null;

  // REUSE: the lead joins an open deal on this project instead of a new one.
  @Field(() => Boolean)
  hasOpenDeal: boolean;

  @Field(() => Boolean)
  isRateLimited: boolean;
}

@InputType('EnsoCreateManualLeadInput')
export class EnsoCreateManualLeadInput {
  // Generated by the form once per lead, so a double submit or a retry after a
  // timeout returns the same lead instead of adding it twice.
  @Field(() => String)
  @IsUUID()
  requestId: string;

  @Field(() => String)
  @IsUUID()
  projectId: string;

  @Field(() => String)
  @IsString()
  @MaxLength(200)
  firstName: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  lastName?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  phoneNumber?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  phoneCallingCode?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsEmail()
  email?: string;

  @Field(() => String)
  @IsUUID()
  manualLeadSourceId: string;

  // When the lead reached the manager. Defaults to now.
  @Field(() => Date, { nullable: true })
  @IsOptional()
  @IsDate()
  occurredAt?: Date;

  // MINE | COLLEAGUE | ROUTING
  @Field(() => String)
  @IsString()
  destination: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsUUID()
  colleagueWorkspaceMemberId?: string;

  // MINE only: LEAD_CLAIMED (default) or CONNECTED.
  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  startStage?: string;

  @Field(() => Date, { nullable: true })
  @IsOptional()
  @IsDate()
  firstContactAt?: Date;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  firstContactChannel?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsUUID()
  referredByPersonId?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsUUID()
  referredByCompanyId?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  referredByName?: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  @MaxLength(5000)
  note?: string;

  // email | sms | whatsapp | call — only what the client agreed to out loud.
  @Field(() => [String], { nullable: true })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  verbalConsentChannels?: string[];
}

// Refusals come back as values, not GraphQL errors, so the form can show the
// message next to the field it is about.
@ObjectType('EnsoManualLeadResult')
export class EnsoManualLeadResultDTO {
  @Field(() => Boolean)
  success: boolean;

  @Field(() => String, { nullable: true })
  error: string | null;

  @Field(() => String, { nullable: true })
  personId: string | null;

  @Field(() => String, { nullable: true })
  opportunityId: string | null;

  @Field(() => String, { nullable: true })
  activityId: string | null;

  @Field(() => Boolean)
  isNewDeal: boolean;

  @Field(() => Boolean)
  isNewPerson: boolean;
}
